### ISSUE TITLE
Buienalarm stopped working?

### ISSUE THREAD

**Issue by sammyke007** [gieljnssns/buienalarm-sensor-homeassistant#40]
**Describe the bug**
I've noticed that buienalarm stopped fetching data. I don't know exactly for how long. Nothing changed configwise...

**Any errors**
```
2025-06-29 10:25:40.462 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform buienalarm is taking over 10 seconds.
2025-06-29 10:25:40.733 WARNING (SyncWorker_0) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
```

**Config yaml**
```
  - platform: buienalarm
    timeframe: 15
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast
```

**Screenshots**
//

**Additional context**
//
