### ISSUE TITLE
module buienalarm not found

### ISSUE THREAD

**Issue by Kouwe-sudo** [gieljnssns/buienalarm-sensor-homeassistant#6]
After loading the integration via HACS and copying:
```
  - platform: buienalarm
    timeframe: 45
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast
```
in the configuration.yaml I get the following ERROR:

'Module buienalarm not found.

I can't find the module 'buienalarm' and so can't Hassio. Do I have to place something in /config/ui-lovelace.yaml or /config/appdaemon/apps/apps.yaml. Normally this isn't the cae or it is stated.
